// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: movie.proto

package moviepbconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	"rpc/internal/movie/proto/moviepb"
	strings "strings"

	connect "connectrpc.com/connect"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MovieServiceName is the fully-qualified name of the MovieService service.
	MovieServiceName = "moviepb.MovieService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MovieServiceCreateMovieProcedure is the fully-qualified name of the MovieService's CreateMovie
	// RPC.
	MovieServiceCreateMovieProcedure = "/moviepb.MovieService/CreateMovie"
	// MovieServiceGetMovieProcedure is the fully-qualified name of the MovieService's GetMovie RPC.
	MovieServiceGetMovieProcedure = "/moviepb.MovieService/GetMovie"
	// MovieServiceUpdateMovieProcedure is the fully-qualified name of the MovieService's UpdateMovie
	// RPC.
	MovieServiceUpdateMovieProcedure = "/moviepb.MovieService/UpdateMovie"
	// MovieServiceDeleteMovieProcedure is the fully-qualified name of the MovieService's DeleteMovie
	// RPC.
	MovieServiceDeleteMovieProcedure = "/moviepb.MovieService/DeleteMovie"
	// MovieServiceListByGenreProcedure is the fully-qualified name of the MovieService's ListByGenre
	// RPC.
	MovieServiceListByGenreProcedure = "/moviepb.MovieService/ListByGenre"
	// MovieServiceListByActorProcedure is the fully-qualified name of the MovieService's ListByActor
	// RPC.
	MovieServiceListByActorProcedure = "/moviepb.MovieService/ListByActor"
)

// MovieServiceClient is a client for the moviepb.MovieService service.
type MovieServiceClient interface {
	CreateMovie(context.Context, *connect.Request[moviepb.CreateMovieRequest]) (*connect.Response[moviepb.CreateMovieResponse], error)
	GetMovie(context.Context, *connect.Request[moviepb.GetMovieRequest]) (*connect.Response[moviepb.GetMovieResponse], error)
	UpdateMovie(context.Context, *connect.Request[moviepb.UpdateMovieRequest]) (*connect.Response[moviepb.UpdateMovieResponse], error)
	DeleteMovie(context.Context, *connect.Request[moviepb.DeleteMovieRequest]) (*connect.Response[moviepb.DeleteMovieResponse], error)
	ListByGenre(context.Context, *connect.Request[moviepb.ListByGenreRequest]) (*connect.Response[moviepb.ListByGenreResponse], error)
	ListByActor(context.Context, *connect.Request[moviepb.ListByActorRequest]) (*connect.Response[moviepb.ListByActorResponse], error)
}

// NewMovieServiceClient constructs a client for the moviepb.MovieService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMovieServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MovieServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	movieServiceMethods := moviepb.File_movie_proto.Services().ByName("MovieService").Methods()
	return &movieServiceClient{
		createMovie: connect.NewClient[moviepb.CreateMovieRequest, moviepb.CreateMovieResponse](
			httpClient,
			baseURL+MovieServiceCreateMovieProcedure,
			connect.WithSchema(movieServiceMethods.ByName("CreateMovie")),
			connect.WithClientOptions(opts...),
		),
		getMovie: connect.NewClient[moviepb.GetMovieRequest, moviepb.GetMovieResponse](
			httpClient,
			baseURL+MovieServiceGetMovieProcedure,
			connect.WithSchema(movieServiceMethods.ByName("GetMovie")),
			connect.WithClientOptions(opts...),
		),
		updateMovie: connect.NewClient[moviepb.UpdateMovieRequest, moviepb.UpdateMovieResponse](
			httpClient,
			baseURL+MovieServiceUpdateMovieProcedure,
			connect.WithSchema(movieServiceMethods.ByName("UpdateMovie")),
			connect.WithClientOptions(opts...),
		),
		deleteMovie: connect.NewClient[moviepb.DeleteMovieRequest, moviepb.DeleteMovieResponse](
			httpClient,
			baseURL+MovieServiceDeleteMovieProcedure,
			connect.WithSchema(movieServiceMethods.ByName("DeleteMovie")),
			connect.WithClientOptions(opts...),
		),
		listByGenre: connect.NewClient[moviepb.ListByGenreRequest, moviepb.ListByGenreResponse](
			httpClient,
			baseURL+MovieServiceListByGenreProcedure,
			connect.WithSchema(movieServiceMethods.ByName("ListByGenre")),
			connect.WithClientOptions(opts...),
		),
		listByActor: connect.NewClient[moviepb.ListByActorRequest, moviepb.ListByActorResponse](
			httpClient,
			baseURL+MovieServiceListByActorProcedure,
			connect.WithSchema(movieServiceMethods.ByName("ListByActor")),
			connect.WithClientOptions(opts...),
		),
	}
}

// movieServiceClient implements MovieServiceClient.
type movieServiceClient struct {
	createMovie *connect.Client[moviepb.CreateMovieRequest, moviepb.CreateMovieResponse]
	getMovie    *connect.Client[moviepb.GetMovieRequest, moviepb.GetMovieResponse]
	updateMovie *connect.Client[moviepb.UpdateMovieRequest, moviepb.UpdateMovieResponse]
	deleteMovie *connect.Client[moviepb.DeleteMovieRequest, moviepb.DeleteMovieResponse]
	listByGenre *connect.Client[moviepb.ListByGenreRequest, moviepb.ListByGenreResponse]
	listByActor *connect.Client[moviepb.ListByActorRequest, moviepb.ListByActorResponse]
}

// CreateMovie calls moviepb.MovieService.CreateMovie.
func (c *movieServiceClient) CreateMovie(ctx context.Context, req *connect.Request[moviepb.CreateMovieRequest]) (*connect.Response[moviepb.CreateMovieResponse], error) {
	return c.createMovie.CallUnary(ctx, req)
}

// GetMovie calls moviepb.MovieService.GetMovie.
func (c *movieServiceClient) GetMovie(ctx context.Context, req *connect.Request[moviepb.GetMovieRequest]) (*connect.Response[moviepb.GetMovieResponse], error) {
	return c.getMovie.CallUnary(ctx, req)
}

// UpdateMovie calls moviepb.MovieService.UpdateMovie.
func (c *movieServiceClient) UpdateMovie(ctx context.Context, req *connect.Request[moviepb.UpdateMovieRequest]) (*connect.Response[moviepb.UpdateMovieResponse], error) {
	return c.updateMovie.CallUnary(ctx, req)
}

// DeleteMovie calls moviepb.MovieService.DeleteMovie.
func (c *movieServiceClient) DeleteMovie(ctx context.Context, req *connect.Request[moviepb.DeleteMovieRequest]) (*connect.Response[moviepb.DeleteMovieResponse], error) {
	return c.deleteMovie.CallUnary(ctx, req)
}

// ListByGenre calls moviepb.MovieService.ListByGenre.
func (c *movieServiceClient) ListByGenre(ctx context.Context, req *connect.Request[moviepb.ListByGenreRequest]) (*connect.Response[moviepb.ListByGenreResponse], error) {
	return c.listByGenre.CallUnary(ctx, req)
}

// ListByActor calls moviepb.MovieService.ListByActor.
func (c *movieServiceClient) ListByActor(ctx context.Context, req *connect.Request[moviepb.ListByActorRequest]) (*connect.Response[moviepb.ListByActorResponse], error) {
	return c.listByActor.CallUnary(ctx, req)
}

// MovieServiceHandler is an implementation of the moviepb.MovieService service.
type MovieServiceHandler interface {
	CreateMovie(context.Context, *connect.Request[moviepb.CreateMovieRequest]) (*connect.Response[moviepb.CreateMovieResponse], error)
	GetMovie(context.Context, *connect.Request[moviepb.GetMovieRequest]) (*connect.Response[moviepb.GetMovieResponse], error)
	UpdateMovie(context.Context, *connect.Request[moviepb.UpdateMovieRequest]) (*connect.Response[moviepb.UpdateMovieResponse], error)
	DeleteMovie(context.Context, *connect.Request[moviepb.DeleteMovieRequest]) (*connect.Response[moviepb.DeleteMovieResponse], error)
	ListByGenre(context.Context, *connect.Request[moviepb.ListByGenreRequest]) (*connect.Response[moviepb.ListByGenreResponse], error)
	ListByActor(context.Context, *connect.Request[moviepb.ListByActorRequest]) (*connect.Response[moviepb.ListByActorResponse], error)
}

// NewMovieServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMovieServiceHandler(svc MovieServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	movieServiceMethods := moviepb.File_movie_proto.Services().ByName("MovieService").Methods()
	movieServiceCreateMovieHandler := connect.NewUnaryHandler(
		MovieServiceCreateMovieProcedure,
		svc.CreateMovie,
		connect.WithSchema(movieServiceMethods.ByName("CreateMovie")),
		connect.WithHandlerOptions(opts...),
	)
	movieServiceGetMovieHandler := connect.NewUnaryHandler(
		MovieServiceGetMovieProcedure,
		svc.GetMovie,
		connect.WithSchema(movieServiceMethods.ByName("GetMovie")),
		connect.WithHandlerOptions(opts...),
	)
	movieServiceUpdateMovieHandler := connect.NewUnaryHandler(
		MovieServiceUpdateMovieProcedure,
		svc.UpdateMovie,
		connect.WithSchema(movieServiceMethods.ByName("UpdateMovie")),
		connect.WithHandlerOptions(opts...),
	)
	movieServiceDeleteMovieHandler := connect.NewUnaryHandler(
		MovieServiceDeleteMovieProcedure,
		svc.DeleteMovie,
		connect.WithSchema(movieServiceMethods.ByName("DeleteMovie")),
		connect.WithHandlerOptions(opts...),
	)
	movieServiceListByGenreHandler := connect.NewUnaryHandler(
		MovieServiceListByGenreProcedure,
		svc.ListByGenre,
		connect.WithSchema(movieServiceMethods.ByName("ListByGenre")),
		connect.WithHandlerOptions(opts...),
	)
	movieServiceListByActorHandler := connect.NewUnaryHandler(
		MovieServiceListByActorProcedure,
		svc.ListByActor,
		connect.WithSchema(movieServiceMethods.ByName("ListByActor")),
		connect.WithHandlerOptions(opts...),
	)
	return "/moviepb.MovieService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MovieServiceCreateMovieProcedure:
			movieServiceCreateMovieHandler.ServeHTTP(w, r)
		case MovieServiceGetMovieProcedure:
			movieServiceGetMovieHandler.ServeHTTP(w, r)
		case MovieServiceUpdateMovieProcedure:
			movieServiceUpdateMovieHandler.ServeHTTP(w, r)
		case MovieServiceDeleteMovieProcedure:
			movieServiceDeleteMovieHandler.ServeHTTP(w, r)
		case MovieServiceListByGenreProcedure:
			movieServiceListByGenreHandler.ServeHTTP(w, r)
		case MovieServiceListByActorProcedure:
			movieServiceListByActorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMovieServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMovieServiceHandler struct{}

func (UnimplementedMovieServiceHandler) CreateMovie(context.Context, *connect.Request[moviepb.CreateMovieRequest]) (*connect.Response[moviepb.CreateMovieResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moviepb.MovieService.CreateMovie is not implemented"))
}

func (UnimplementedMovieServiceHandler) GetMovie(context.Context, *connect.Request[moviepb.GetMovieRequest]) (*connect.Response[moviepb.GetMovieResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moviepb.MovieService.GetMovie is not implemented"))
}

func (UnimplementedMovieServiceHandler) UpdateMovie(context.Context, *connect.Request[moviepb.UpdateMovieRequest]) (*connect.Response[moviepb.UpdateMovieResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moviepb.MovieService.UpdateMovie is not implemented"))
}

func (UnimplementedMovieServiceHandler) DeleteMovie(context.Context, *connect.Request[moviepb.DeleteMovieRequest]) (*connect.Response[moviepb.DeleteMovieResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moviepb.MovieService.DeleteMovie is not implemented"))
}

func (UnimplementedMovieServiceHandler) ListByGenre(context.Context, *connect.Request[moviepb.ListByGenreRequest]) (*connect.Response[moviepb.ListByGenreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moviepb.MovieService.ListByGenre is not implemented"))
}

func (UnimplementedMovieServiceHandler) ListByActor(context.Context, *connect.Request[moviepb.ListByActorRequest]) (*connect.Response[moviepb.ListByActorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("moviepb.MovieService.ListByActor is not implemented"))
}
