// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: movie.proto

package moviepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Plot          string                 `protobuf:"bytes,4,opt,name=plot,proto3" json:"plot,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Cast          []string               `protobuf:"bytes,6,rep,name=cast,proto3" json:"cast,omitempty"`
	Directors     []string               `protobuf:"bytes,7,rep,name=directors,proto3" json:"directors,omitempty"`
	Rated         string                 `protobuf:"bytes,8,opt,name=rated,proto3" json:"rated,omitempty"`
	Runtime       int32                  `protobuf:"varint,9,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieReq) Reset() {
	*x = MovieReq{}
	mi := &file_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieReq) ProtoMessage() {}

func (x *MovieReq) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieReq.ProtoReflect.Descriptor instead.
func (*MovieReq) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{0}
}

func (x *MovieReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieReq) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MovieReq) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

func (x *MovieReq) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieReq) GetCast() []string {
	if x != nil {
		return x.Cast
	}
	return nil
}

func (x *MovieReq) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *MovieReq) GetRated() string {
	if x != nil {
		return x.Rated
	}
	return ""
}

func (x *MovieReq) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

type MovieRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Plot          string                 `protobuf:"bytes,4,opt,name=plot,proto3" json:"plot,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Cast          []string               `protobuf:"bytes,6,rep,name=cast,proto3" json:"cast,omitempty"`
	Directors     []string               `protobuf:"bytes,7,rep,name=directors,proto3" json:"directors,omitempty"`
	Rated         string                 `protobuf:"bytes,8,opt,name=rated,proto3" json:"rated,omitempty"`
	Runtime       int32                  `protobuf:"varint,9,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieRes) Reset() {
	*x = MovieRes{}
	mi := &file_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieRes) ProtoMessage() {}

func (x *MovieRes) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieRes.ProtoReflect.Descriptor instead.
func (*MovieRes) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{1}
}

func (x *MovieRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MovieRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieRes) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MovieRes) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

func (x *MovieRes) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieRes) GetCast() []string {
	if x != nil {
		return x.Cast
	}
	return nil
}

func (x *MovieRes) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *MovieRes) GetRated() string {
	if x != nil {
		return x.Rated
	}
	return ""
}

func (x *MovieRes) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

type CreateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieReq              `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMovieRequest) GetMovie() *MovieReq {
	if x != nil {
		return x.Movie
	}
	return nil
}

type CreateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieRes              `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieResponse) Reset() {
	*x = CreateMovieResponse{}
	mi := &file_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieResponse) ProtoMessage() {}

func (x *CreateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieResponse.ProtoReflect.Descriptor instead.
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMovieResponse) GetMovie() *MovieRes {
	if x != nil {
		return x.Movie
	}
	return nil
}

type GetMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	mi := &file_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieRes              `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	mi := &file_movie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{5}
}

func (x *GetMovieResponse) GetMovie() *MovieRes {
	if x != nil {
		return x.Movie
	}
	return nil
}

type UpdateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie         *MovieReq              `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	mi := &file_movie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMovieRequest) GetMovie() *MovieReq {
	if x != nil {
		return x.Movie
	}
	return nil
}

type UpdateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieRes              `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieResponse) Reset() {
	*x = UpdateMovieResponse{}
	mi := &file_movie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieResponse) ProtoMessage() {}

func (x *UpdateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieResponse.ProtoReflect.Descriptor instead.
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMovieResponse) GetMovie() *MovieRes {
	if x != nil {
		return x.Movie
	}
	return nil
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_movie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	mi := &file_movie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMovieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListByGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genre         string                 `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByGenreRequest) Reset() {
	*x = ListByGenreRequest{}
	mi := &file_movie_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByGenreRequest) ProtoMessage() {}

func (x *ListByGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByGenreRequest.ProtoReflect.Descriptor instead.
func (*ListByGenreRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{10}
}

func (x *ListByGenreRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type ListByGenreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*MovieRes            `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByGenreResponse) Reset() {
	*x = ListByGenreResponse{}
	mi := &file_movie_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByGenreResponse) ProtoMessage() {}

func (x *ListByGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByGenreResponse.ProtoReflect.Descriptor instead.
func (*ListByGenreResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{11}
}

func (x *ListByGenreResponse) GetMovies() []*MovieRes {
	if x != nil {
		return x.Movies
	}
	return nil
}

type ListByActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByActorRequest) Reset() {
	*x = ListByActorRequest{}
	mi := &file_movie_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByActorRequest) ProtoMessage() {}

func (x *ListByActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByActorRequest.ProtoReflect.Descriptor instead.
func (*ListByActorRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{12}
}

func (x *ListByActorRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type ListByActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*MovieRes            `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByActorResponse) Reset() {
	*x = ListByActorResponse{}
	mi := &file_movie_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByActorResponse) ProtoMessage() {}

func (x *ListByActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByActorResponse.ProtoReflect.Descriptor instead.
func (*ListByActorResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{13}
}

func (x *ListByActorResponse) GetMovies() []*MovieRes {
	if x != nil {
		return x.Movies
	}
	return nil
}

var File_movie_proto protoreflect.FileDescriptor

const file_movie_proto_rawDesc = "" +
	"\n" +
	"\vmovie.proto\x12\amoviepb\"\xc2\x01\n" +
	"\bMovieReq\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x12\n" +
	"\x04plot\x18\x04 \x01(\tR\x04plot\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12\x12\n" +
	"\x04cast\x18\x06 \x03(\tR\x04cast\x12\x1c\n" +
	"\tdirectors\x18\a \x03(\tR\tdirectors\x12\x14\n" +
	"\x05rated\x18\b \x01(\tR\x05rated\x12\x18\n" +
	"\aruntime\x18\t \x01(\x05R\aruntime\"\xd2\x01\n" +
	"\bMovieRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x12\n" +
	"\x04plot\x18\x04 \x01(\tR\x04plot\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12\x12\n" +
	"\x04cast\x18\x06 \x03(\tR\x04cast\x12\x1c\n" +
	"\tdirectors\x18\a \x03(\tR\tdirectors\x12\x14\n" +
	"\x05rated\x18\b \x01(\tR\x05rated\x12\x18\n" +
	"\aruntime\x18\t \x01(\x05R\aruntime\"=\n" +
	"\x12CreateMovieRequest\x12'\n" +
	"\x05movie\x18\x01 \x01(\v2\x11.moviepb.MovieReqR\x05movie\">\n" +
	"\x13CreateMovieResponse\x12'\n" +
	"\x05movie\x18\x01 \x01(\v2\x11.moviepb.MovieResR\x05movie\"!\n" +
	"\x0fGetMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x10GetMovieResponse\x12'\n" +
	"\x05movie\x18\x01 \x01(\v2\x11.moviepb.MovieResR\x05movie\"M\n" +
	"\x12UpdateMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x05movie\x18\x02 \x01(\v2\x11.moviepb.MovieReqR\x05movie\">\n" +
	"\x13UpdateMovieResponse\x12'\n" +
	"\x05movie\x18\x01 \x01(\v2\x11.moviepb.MovieResR\x05movie\"$\n" +
	"\x12DeleteMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteMovieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x12ListByGenreRequest\x12\x14\n" +
	"\x05genre\x18\x01 \x01(\tR\x05genre\"@\n" +
	"\x13ListByGenreResponse\x12)\n" +
	"\x06movies\x18\x01 \x03(\v2\x11.moviepb.MovieResR\x06movies\"*\n" +
	"\x12ListByActorRequest\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\"@\n" +
	"\x13ListByActorResponse\x12)\n" +
	"\x06movies\x18\x01 \x03(\v2\x11.moviepb.MovieResR\x06movies2\xcd\x03\n" +
	"\fMovieService\x12J\n" +
	"\vCreateMovie\x12\x1b.moviepb.CreateMovieRequest\x1a\x1c.moviepb.CreateMovieResponse\"\x00\x12A\n" +
	"\bGetMovie\x12\x18.moviepb.GetMovieRequest\x1a\x19.moviepb.GetMovieResponse\"\x00\x12J\n" +
	"\vUpdateMovie\x12\x1b.moviepb.UpdateMovieRequest\x1a\x1c.moviepb.UpdateMovieResponse\"\x00\x12J\n" +
	"\vDeleteMovie\x12\x1b.moviepb.DeleteMovieRequest\x1a\x1c.moviepb.DeleteMovieResponse\"\x00\x12J\n" +
	"\vListByGenre\x12\x1b.moviepb.ListByGenreRequest\x1a\x1c.moviepb.ListByGenreResponse\"\x00\x12J\n" +
	"\vListByActor\x12\x1b.moviepb.ListByActorRequest\x1a\x1c.moviepb.ListByActorResponse\"\x00B%Z#./backend-go/internal/proto/moviepbb\x06proto3"

var (
	file_movie_proto_rawDescOnce sync.Once
	file_movie_proto_rawDescData []byte
)

func file_movie_proto_rawDescGZIP() []byte {
	file_movie_proto_rawDescOnce.Do(func() {
		file_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)))
	})
	return file_movie_proto_rawDescData
}

var file_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_movie_proto_goTypes = []any{
	(*MovieReq)(nil),            // 0: moviepb.MovieReq
	(*MovieRes)(nil),            // 1: moviepb.MovieRes
	(*CreateMovieRequest)(nil),  // 2: moviepb.CreateMovieRequest
	(*CreateMovieResponse)(nil), // 3: moviepb.CreateMovieResponse
	(*GetMovieRequest)(nil),     // 4: moviepb.GetMovieRequest
	(*GetMovieResponse)(nil),    // 5: moviepb.GetMovieResponse
	(*UpdateMovieRequest)(nil),  // 6: moviepb.UpdateMovieRequest
	(*UpdateMovieResponse)(nil), // 7: moviepb.UpdateMovieResponse
	(*DeleteMovieRequest)(nil),  // 8: moviepb.DeleteMovieRequest
	(*DeleteMovieResponse)(nil), // 9: moviepb.DeleteMovieResponse
	(*ListByGenreRequest)(nil),  // 10: moviepb.ListByGenreRequest
	(*ListByGenreResponse)(nil), // 11: moviepb.ListByGenreResponse
	(*ListByActorRequest)(nil),  // 12: moviepb.ListByActorRequest
	(*ListByActorResponse)(nil), // 13: moviepb.ListByActorResponse
}
var file_movie_proto_depIdxs = []int32{
	0,  // 0: moviepb.CreateMovieRequest.movie:type_name -> moviepb.MovieReq
	1,  // 1: moviepb.CreateMovieResponse.movie:type_name -> moviepb.MovieRes
	1,  // 2: moviepb.GetMovieResponse.movie:type_name -> moviepb.MovieRes
	0,  // 3: moviepb.UpdateMovieRequest.movie:type_name -> moviepb.MovieReq
	1,  // 4: moviepb.UpdateMovieResponse.movie:type_name -> moviepb.MovieRes
	1,  // 5: moviepb.ListByGenreResponse.movies:type_name -> moviepb.MovieRes
	1,  // 6: moviepb.ListByActorResponse.movies:type_name -> moviepb.MovieRes
	2,  // 7: moviepb.MovieService.CreateMovie:input_type -> moviepb.CreateMovieRequest
	4,  // 8: moviepb.MovieService.GetMovie:input_type -> moviepb.GetMovieRequest
	6,  // 9: moviepb.MovieService.UpdateMovie:input_type -> moviepb.UpdateMovieRequest
	8,  // 10: moviepb.MovieService.DeleteMovie:input_type -> moviepb.DeleteMovieRequest
	10, // 11: moviepb.MovieService.ListByGenre:input_type -> moviepb.ListByGenreRequest
	12, // 12: moviepb.MovieService.ListByActor:input_type -> moviepb.ListByActorRequest
	3,  // 13: moviepb.MovieService.CreateMovie:output_type -> moviepb.CreateMovieResponse
	5,  // 14: moviepb.MovieService.GetMovie:output_type -> moviepb.GetMovieResponse
	7,  // 15: moviepb.MovieService.UpdateMovie:output_type -> moviepb.UpdateMovieResponse
	9,  // 16: moviepb.MovieService.DeleteMovie:output_type -> moviepb.DeleteMovieResponse
	11, // 17: moviepb.MovieService.ListByGenre:output_type -> moviepb.ListByGenreResponse
	13, // 18: moviepb.MovieService.ListByActor:output_type -> moviepb.ListByActorResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_movie_proto_init() }
func file_movie_proto_init() {
	if File_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_proto_goTypes,
		DependencyIndexes: file_movie_proto_depIdxs,
		MessageInfos:      file_movie_proto_msgTypes,
	}.Build()
	File_movie_proto = out.File
	file_movie_proto_goTypes = nil
	file_movie_proto_depIdxs = nil
}
